name: maven-build
on: push
jobs:
 build-package:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code in repo
     uses: actions/checkout@v3
   - name: setup java sdk
     uses: actions/setup-java@v1
     with:
      java-version: 1.8
   - name: check maven version
     run: mvn -v
   - name: compile java file in main
     run: mvn compile
   - name: test code with test cases
     run: | 
      mvn test-compile
      mvn test
   - name: packaging the maven code into jar file
     run: mvn package
   - name: listing file in directory
     run: ls -a
   - name: to target, list files, execute jar
     run: |
      cd target
      ls -a
      echo "executing jar file"
      java -jar wave2app-1.0-SNAPSHOT.jar
